baseurl = "https://monicaspisar.com/"
languageCode = "en-us"
languageName = "English"
title = "Monica Spisar"
theme = "loveit"

summaryLength = 10
footnotereturnlinkcontents = "↩"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""

  [[menu.main]]
    weight = 10
    identifier = "etc"
    pre = ""
    post = ""
    name = "Etc"
    url = "/etc/"
    title = ""

  [[menu.main]]
    weight = 40
    identifier = "publications"
    pre = ""
    post = ""
    name = "Publications"
    url = "/publications/"
    title = ""    

  [[menu.main]]
    weight = 50
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""

  [[menu.main]]
    weight = 99
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://linkedin.com/in/monicaspisar"
    title = "LinkedIn"

  [[menu.main]]
    weight = 99
    identifier = "twitter"
    pre = "<i class='fab fa-twitter fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://twitter.com/msyvr"
    title = "Twitter"    

  [[menu.main]]
    weight = 100
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://github.com/msyvr"
    title = "Github"

[markup]
	[markup.highlight]
	noClasses = false

[params]
  author = "Monica Spisar"
  link = "https://monicaspisar.com"
  title = "Monica Spisar"
  description = "Monica Spisar's website"
  defaultTheme = "auto"

  [params.header]
    [params.header.title]
      logo = ""
      name = "Monica Spisar"
      typeit = false
  
  [params.footer]
    enable = true
    hugo = false
    copyright = true
    author = true
    name = true
    since = 2024
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0 |</a> <a href="https://www.recurse.com/">&#x2661 <img width="10px" src="/images/rc_static.svg"> &#x2661</img></a>'

[params.section]
  paginate = 25
  dateFormat = "01-02"

[params.list]
  paginate = 25

[params.app]
  title = "Monica Spisar"

[params.search]
  enable = false # TODO

[params.home]

  [params.home.posts]
    paginate = 25

  [params.home.profile]
    enable = true
    avatarURL = "/images/Avatar_ms_bw.png"
    # gravatarEmail = "monicaspisar@gmail.com"
    subtitle = ""
    typeit = false
    social = true

  [params.social]
    LinkedIn = "https://linkedin.com/in/monicaspisar"
    GitHub = "msyvr"
    Email = "msyvrr@gmail.com"
    Twitter = "msyvr"
    RSS = false
    Recurse = ""

  [params.page]
    [params.page.toc]
      enable = true

    [params.page.code]
      maxShownLines = -1

    [params.page.comment]
      enable = false
      [params.page.comment.utterances]
        enable = true
        repo = "msyvr/my-website"
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = false
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = true
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
